skilled_team:
  log_level: 'DEBUG'
  one_size_validation: False
  player_id_index: 0
  first_name: 1
  last_name: 2
  skills:
    indexes: [3, 4, 5, 6, 7, 8]
    manual_weights: None
  players_per_team: 5
  balancer:
    min_val_sk_set_size: 3
    max_failures : 100000