skilled_team:
  log_level: 'DEBUG'
  one_size_validation: True
  player_id_index: 0
  first_name: 1
  last_name: 2
  extra_field: [3, 10, 11]

  skills:
    indexes: [4, 5, 6, 7, 8, 9]
    manual_weights: None
  players_per_team: 5
  balancer:
    min_val_sk_set_size: 3
    max_failures : 1000
output:
  format: 'csv'